CREATE DATABASE ROADWAY_TRAVELS;
USE ROADWAY_TRAVELS;
CREATE TABLE BUS (BNO INT PRIMARY KEY, BNAME VARCHAR(20), SOURCE VARCHAR(20),DESTINATION VARCHAR(20),ARRTIME TIME,DEPTIME TIME);
CREATE TABLE PASSENGER (PID INT PRIMARY KEY, PNAME VARCHAR(20), AGE INT, GENDER VARCHAR(10), PHNO NUMERIC, EMAIL VARCHAR(30));
CREATE TABLE TICKET (TID INT PRIMARY KEY, PID INT, BNO INT, BDATE DATE, PRICE INT, FOREIGN KEY(PID) REFERENCES PASSENGER(PID) ON UPDATE CASCADE ON DELETE CASCADE,FOREIGN KEY(BNO) REFERENCES BUS(BNO) ON UPDATE CASCADE ON DELETE CASCADE);
CREATE TABLE RESERVATION (TID INT, JDATE DATE, STATUS VARCHAR(20), REMARKS VARCHAR(50), FOREIGN KEY(TID) REFERENCES TICKET(TID) ON UPDATE CASCADE ON DELETE CASCADE);
CREATE TABLE  CANCELLATION (TID INT, JDATE DATE, STATUS VARCHAR(20),REMARKS VARCHAR(50), FOREIGN KEY(TID) REFERENCES TICKET(TID) ON UPDATE CASCADE ON DELETE CASCADE);
SELECT * FROM CANCELLATION;
